export const socialPosts = [
  {
    name: 'Vana',
    twitter: '@HavanaRamal',
    text: 'Just got off a call in tears because it seems like I am finally going to be able to get decent and consistent therapy soon. Thank you @YouAreRAD😭🙌',
    time: '11:40 AM',
    date: 'Aug 6, 2021',
    comments: '8',
    retweets: '1',
    likes: '202',
    photo: 'https://res.cloudinary.com/df23ubjbb/image/upload/v1638318953/Vana.jpg',
  },
  {
    name: 'John Robbins - BLM🖤',
    twitter: '@J5isLive',
    text: "I'm thankful for @YouAreRAD, which has helped me return to going to therapy on a weekly basis and helps pay for a number of the expenses related to my mental health needs.",
    time: '10:15 AM',
    date: 'Aug 5, 2021',
    comments: '83',
    retweets: '1',
    likes: '5',
    photo: 'https://res.cloudinary.com/df23ubjbb/image/upload/v1638319109/John.jpg',
  },
  {
    name: 'Vana',
    twitter: '@HavanaRamal',
    text: 'Just got off a call in tears because it seems like I am finally going to be able to get decent and consistent therapy soon. Thank you @YouAreRAD😭🙌',
    time: '11:40 AM',
    date: 'Aug 6, 2021',
    comments: '8',
    retweets: '1',
    likes: '202',
    photo: 'https://res.cloudinary.com/df23ubjbb/image/upload/v1638318953/Vana.jpg',
  },
]
